/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.daw1.ismael.gui;

/**
 *
 * @author ismac
 */
public class MainGUI extends javax.swing.JFrame {

    private static final java.awt.Color COLOR_ROJO = new java.awt.Color(255,51,51);
    private static final java.awt.Color COLOR_AMARILLO = new java.awt.Color(239,208,60);
    private static final java.awt.Color COLOR_VERDE = new java.awt.Color(0,204,51);
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainJPanel = new javax.swing.JPanel();
        LetrasJPanel = new javax.swing.JPanel();
        JLabel1_1 = new javax.swing.JLabel();
        JLabel1_2 = new javax.swing.JLabel();
        JLabel1_3 = new javax.swing.JLabel();
        JLabel1_4 = new javax.swing.JLabel();
        JLabel1_5 = new javax.swing.JLabel();
        JLabel1_6 = new javax.swing.JLabel();
        JLabel2_1 = new javax.swing.JLabel();
        JLabel2_2 = new javax.swing.JLabel();
        JLabel2_3 = new javax.swing.JLabel();
        JLabel2_4 = new javax.swing.JLabel();
        JLabel2_5 = new javax.swing.JLabel();
        JLabel2_6 = new javax.swing.JLabel();
        JLabel3_1 = new javax.swing.JLabel();
        JLabel3_2 = new javax.swing.JLabel();
        JLabel3_3 = new javax.swing.JLabel();
        JLabel3_4 = new javax.swing.JLabel();
        JLabel3_5 = new javax.swing.JLabel();
        JLabel3_6 = new javax.swing.JLabel();
        JLabel4_1 = new javax.swing.JLabel();
        JLabel4_2 = new javax.swing.JLabel();
        JLabel4_3 = new javax.swing.JLabel();
        JLabel4_4 = new javax.swing.JLabel();
        JLabel4_5 = new javax.swing.JLabel();
        JLabel4_6 = new javax.swing.JLabel();
        JLabel5_1 = new javax.swing.JLabel();
        JLabel5_2 = new javax.swing.JLabel();
        JLabel5_3 = new javax.swing.JLabel();
        JLabel5_4 = new javax.swing.JLabel();
        JLabel5_5 = new javax.swing.JLabel();
        JLabel5_6 = new javax.swing.JLabel();
        BottomJPanel = new javax.swing.JPanel();
        EstadoJPanel = new javax.swing.JPanel();
        MalJPanel = new javax.swing.JPanel();
        MalJLabel = new javax.swing.JLabel();
        ExistenJPanel = new javax.swing.JPanel();
        ExisteJLabel = new javax.swing.JLabel();
        BienJPanel = new javax.swing.JPanel();
        BienJLabel = new javax.swing.JLabel();
        InputJPanel = new javax.swing.JPanel();
        PalabraTextField = new javax.swing.JTextField();
        EnviarButtom = new javax.swing.JButton();
        ExitoJPanel = new javax.swing.JPanel();
        FinalJLabel = new javax.swing.JLabel();
        ErrorJPanel = new javax.swing.JPanel();
        ErrorJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DAW1 WORDLE ISMAEL");

        MainJPanel.setLayout(new java.awt.BorderLayout());

        LetrasJPanel.setLayout(new java.awt.GridLayout(6, 5));

        JLabel1_1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel1_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel1_1.setText("A");
        LetrasJPanel.add(JLabel1_1);

        JLabel1_2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel1_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel1_2.setText("A");
        LetrasJPanel.add(JLabel1_2);

        JLabel1_3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel1_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel1_3.setText("A");
        LetrasJPanel.add(JLabel1_3);

        JLabel1_4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel1_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel1_4.setText("A");
        LetrasJPanel.add(JLabel1_4);

        JLabel1_5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel1_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel1_5.setText("A");
        LetrasJPanel.add(JLabel1_5);

        JLabel1_6.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel1_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel1_6.setText("A");
        LetrasJPanel.add(JLabel1_6);

        JLabel2_1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel2_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel2_1.setText("A");
        LetrasJPanel.add(JLabel2_1);

        JLabel2_2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel2_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel2_2.setText("A");
        LetrasJPanel.add(JLabel2_2);

        JLabel2_3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel2_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel2_3.setText("A");
        LetrasJPanel.add(JLabel2_3);

        JLabel2_4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel2_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel2_4.setText("A");
        LetrasJPanel.add(JLabel2_4);

        JLabel2_5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel2_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel2_5.setText("A");
        LetrasJPanel.add(JLabel2_5);

        JLabel2_6.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel2_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel2_6.setText("A");
        LetrasJPanel.add(JLabel2_6);

        JLabel3_1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel3_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel3_1.setText("A");
        LetrasJPanel.add(JLabel3_1);

        JLabel3_2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel3_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel3_2.setText("A");
        LetrasJPanel.add(JLabel3_2);

        JLabel3_3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel3_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel3_3.setText("A");
        LetrasJPanel.add(JLabel3_3);

        JLabel3_4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel3_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel3_4.setText("A");
        LetrasJPanel.add(JLabel3_4);

        JLabel3_5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel3_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel3_5.setText("A");
        LetrasJPanel.add(JLabel3_5);

        JLabel3_6.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel3_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel3_6.setText("A");
        LetrasJPanel.add(JLabel3_6);

        JLabel4_1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel4_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel4_1.setText("A");
        LetrasJPanel.add(JLabel4_1);

        JLabel4_2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel4_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel4_2.setText("A");
        LetrasJPanel.add(JLabel4_2);

        JLabel4_3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel4_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel4_3.setText("A");
        LetrasJPanel.add(JLabel4_3);

        JLabel4_4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel4_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel4_4.setText("A");
        LetrasJPanel.add(JLabel4_4);

        JLabel4_5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel4_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel4_5.setText("A");
        LetrasJPanel.add(JLabel4_5);

        JLabel4_6.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel4_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel4_6.setText("A");
        LetrasJPanel.add(JLabel4_6);

        JLabel5_1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel5_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel5_1.setText("A");
        LetrasJPanel.add(JLabel5_1);

        JLabel5_2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel5_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel5_2.setText("A");
        LetrasJPanel.add(JLabel5_2);

        JLabel5_3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel5_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel5_3.setText("A");
        LetrasJPanel.add(JLabel5_3);

        JLabel5_4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel5_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel5_4.setText("A");
        LetrasJPanel.add(JLabel5_4);

        JLabel5_5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel5_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel5_5.setText("A");
        LetrasJPanel.add(JLabel5_5);

        JLabel5_6.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel5_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel5_6.setText("A");
        LetrasJPanel.add(JLabel5_6);

        MainJPanel.add(LetrasJPanel, java.awt.BorderLayout.CENTER);

        BottomJPanel.setPreferredSize(new java.awt.Dimension(200, 112));
        BottomJPanel.setLayout(new java.awt.GridLayout(2, 2));

        EstadoJPanel.setLayout(new java.awt.GridLayout(3, 0));

        MalJPanel.setLayout(new java.awt.GridLayout());

        MalJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        MalJLabel.setForeground(new java.awt.Color(255, 51, 51));
        MalJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MalJLabel.setText("jLabel1");
        MalJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        MalJPanel.add(MalJLabel);

        EstadoJPanel.add(MalJPanel);

        ExistenJPanel.setLayout(new java.awt.GridLayout());

        ExisteJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ExisteJLabel.setForeground(new java.awt.Color(239, 208, 60));
        ExisteJLabel.setText("jLabel1");
        ExistenJPanel.add(ExisteJLabel);

        EstadoJPanel.add(ExistenJPanel);

        BienJPanel.setLayout(new java.awt.GridLayout());

        BienJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BienJLabel.setForeground(new java.awt.Color(0, 204, 51));
        BienJLabel.setText("jLabel1");
        BienJPanel.add(BienJLabel);

        EstadoJPanel.add(BienJPanel);

        BottomJPanel.add(EstadoJPanel);

        PalabraTextField.setPreferredSize(new java.awt.Dimension(120, 22));
        InputJPanel.add(PalabraTextField);

        EnviarButtom.setText("Enviar");
        InputJPanel.add(EnviarButtom);

        BottomJPanel.add(InputJPanel);

        ExitoJPanel.setLayout(new java.awt.GridBagLayout());

        FinalJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FinalJLabel.setForeground(new java.awt.Color(102, 204, 0));
        ExitoJPanel.add(FinalJLabel, new java.awt.GridBagConstraints());

        BottomJPanel.add(ExitoJPanel);

        ErrorJPanel.setLayout(new java.awt.GridBagLayout());

        ErrorJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ErrorJLabel.setForeground(new java.awt.Color(204, 0, 0));
        ErrorJPanel.add(ErrorJLabel, new java.awt.GridBagConstraints());

        BottomJPanel.add(ErrorJPanel);

        MainJPanel.add(BottomJPanel, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BienJLabel;
    private javax.swing.JPanel BienJPanel;
    private javax.swing.JPanel BottomJPanel;
    private javax.swing.JButton EnviarButtom;
    private javax.swing.JLabel ErrorJLabel;
    private javax.swing.JPanel ErrorJPanel;
    private javax.swing.JPanel EstadoJPanel;
    private javax.swing.JLabel ExisteJLabel;
    private javax.swing.JPanel ExistenJPanel;
    private javax.swing.JPanel ExitoJPanel;
    private javax.swing.JLabel FinalJLabel;
    private javax.swing.JPanel InputJPanel;
    private javax.swing.JLabel JLabel1_1;
    private javax.swing.JLabel JLabel1_2;
    private javax.swing.JLabel JLabel1_3;
    private javax.swing.JLabel JLabel1_4;
    private javax.swing.JLabel JLabel1_5;
    private javax.swing.JLabel JLabel1_6;
    private javax.swing.JLabel JLabel2_1;
    private javax.swing.JLabel JLabel2_2;
    private javax.swing.JLabel JLabel2_3;
    private javax.swing.JLabel JLabel2_4;
    private javax.swing.JLabel JLabel2_5;
    private javax.swing.JLabel JLabel2_6;
    private javax.swing.JLabel JLabel3_1;
    private javax.swing.JLabel JLabel3_2;
    private javax.swing.JLabel JLabel3_3;
    private javax.swing.JLabel JLabel3_4;
    private javax.swing.JLabel JLabel3_5;
    private javax.swing.JLabel JLabel3_6;
    private javax.swing.JLabel JLabel4_1;
    private javax.swing.JLabel JLabel4_2;
    private javax.swing.JLabel JLabel4_3;
    private javax.swing.JLabel JLabel4_4;
    private javax.swing.JLabel JLabel4_5;
    private javax.swing.JLabel JLabel4_6;
    private javax.swing.JLabel JLabel5_1;
    private javax.swing.JLabel JLabel5_2;
    private javax.swing.JLabel JLabel5_3;
    private javax.swing.JLabel JLabel5_4;
    private javax.swing.JLabel JLabel5_5;
    private javax.swing.JLabel JLabel5_6;
    private javax.swing.JPanel LetrasJPanel;
    private javax.swing.JPanel MainJPanel;
    private javax.swing.JLabel MalJLabel;
    private javax.swing.JPanel MalJPanel;
    private javax.swing.JTextField PalabraTextField;
    // End of variables declaration//GEN-END:variables
}
