/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.daw1.ismael.gui;

import org.daw1.ismael.clases.Motor;

/**
 *
 * @author ismac
 */
public class ModificarMotor extends javax.swing.JDialog {

    private Motor tipoMotor = MainGUI.getTipoMotor();
     private static final java.awt.Color COLOR_ROJO = new java.awt.Color(255,51,51);
    private static final java.awt.Color COLOR_AMARILLO = new java.awt.Color(239,208,60);
    private static final java.awt.Color COLOR_VERDE = new java.awt.Color(0,204,51);
    private static final java.awt.Color COLOR_DEFAULT = new java.awt.Color(187,187,187);
    
    public ModificarMotor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJPanel = new javax.swing.JPanel();
        cuerpoJPanel = new javax.swing.JPanel();
        anadirJPanel = new javax.swing.JPanel();
        insertarJPanel = new javax.swing.JPanel();
        anadirTextField = new javax.swing.JTextField();
        anadirButtom = new javax.swing.JButton();
        estadoInsertarJPanel = new javax.swing.JPanel();
        estadoInsertarJLabel = new javax.swing.JLabel();
        borrarJPanel = new javax.swing.JPanel();
        borradoJPanel = new javax.swing.JPanel();
        borrarJText = new javax.swing.JTextField();
        borrarJButtom = new javax.swing.JButton();
        estadoJPanel = new javax.swing.JPanel();
        estadoJLabel = new javax.swing.JLabel();
        tituloJPanel = new javax.swing.JPanel();
        tituloJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mainJPanel.setLayout(new java.awt.BorderLayout());

        cuerpoJPanel.setLayout(new java.awt.GridLayout(2, 1));

        anadirJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        anadirJPanel.setToolTipText("Alta palabra");
        anadirJPanel.setLayout(new java.awt.GridLayout(2, 1));

        anadirTextField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        anadirTextField.setPreferredSize(new java.awt.Dimension(160, 23));
        insertarJPanel.add(anadirTextField);

        anadirButtom.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        anadirButtom.setText("Añadir");
        anadirButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirButtomActionPerformed(evt);
            }
        });
        insertarJPanel.add(anadirButtom);

        anadirJPanel.add(insertarJPanel);

        estadoInsertarJPanel.setLayout(new java.awt.GridBagLayout());
        estadoInsertarJPanel.add(estadoInsertarJLabel, new java.awt.GridBagConstraints());

        anadirJPanel.add(estadoInsertarJPanel);

        cuerpoJPanel.add(anadirJPanel);

        borrarJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        borrarJPanel.setToolTipText("Baja Palabra");
        borrarJPanel.setLayout(new java.awt.GridLayout(2, 1));

        borrarJText.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        borrarJText.setPreferredSize(new java.awt.Dimension(160, 23));
        borradoJPanel.add(borrarJText);

        borrarJButtom.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        borrarJButtom.setText("Borrar");
        borrarJButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarJButtomActionPerformed(evt);
            }
        });
        borradoJPanel.add(borrarJButtom);

        borrarJPanel.add(borradoJPanel);

        estadoJPanel.setLayout(new java.awt.GridBagLayout());
        estadoJPanel.add(estadoJLabel, new java.awt.GridBagConstraints());

        borrarJPanel.add(estadoJPanel);

        cuerpoJPanel.add(borrarJPanel);

        mainJPanel.add(cuerpoJPanel, java.awt.BorderLayout.CENTER);

        tituloJPanel.setLayout(new java.awt.GridBagLayout());

        tituloJLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        tituloJLabel.setText("Gestion Motor");
        tituloJPanel.add(tituloJLabel, new java.awt.GridBagConstraints());

        mainJPanel.add(tituloJPanel, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anadirButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirButtomActionPerformed
        this.estadoInsertarJLabel.setVisible(false);
        if(!tipoMotor.existsWord(this.anadirTextField.getText())){
            if(this.anadirTextField.getText().length() != 5){
                this.estadoInsertarJLabel.setText("La palabra tiene que ser de 5 letras");
                this.estadoInsertarJLabel.setForeground(COLOR_ROJO);
                this.estadoInsertarJLabel.setVisible(true);
            }else if(!this.anadirTextField.getText().matches("[A-Za-z]{5}")){
                this.estadoInsertarJLabel.setText("La palabra solo puede llevar letras");
                this.estadoInsertarJLabel.setForeground(COLOR_ROJO);
                this.estadoInsertarJLabel.setVisible(true);
            }else{
                tipoMotor.addWord(this.anadirTextField.getText());
                this.estadoInsertarJLabel.setText("La palabra fue agregada con exito");
                this.estadoInsertarJLabel.setForeground(COLOR_VERDE);
                this.estadoInsertarJLabel.setVisible(true);
            } 
        }else{
            this.estadoInsertarJLabel.setText("La palabra ya existe no puedes agregarla");
            this.estadoInsertarJLabel.setForeground(COLOR_ROJO);
            this.estadoInsertarJLabel.setVisible(true);
        }
    }//GEN-LAST:event_anadirButtomActionPerformed

    private void borrarJButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarJButtomActionPerformed
        this.estadoJLabel.setVisible(false);
        if(tipoMotor.existsWord(this.borrarJText.getText())){
            if(this.borrarJText.getText().length() != 5){
                this.estadoJLabel.setText("La palabra tiene que ser de 5 letras");
                this.estadoJLabel.setForeground(COLOR_ROJO);
                this.estadoJLabel.setVisible(true);
            }else if(!this.borrarJText.getText().matches("[A-Za-z]{5}")){
                this.estadoJLabel.setText("La palabra solo puede llevar letras");
                this.estadoJLabel.setForeground(COLOR_ROJO);
                this.estadoJLabel.setVisible(true);
            }else{
                tipoMotor.removeWord(this.borrarJText.getText().toString());
                this.estadoJLabel.setText("La palabra fue borrada con exito");
                this.estadoJLabel.setForeground(COLOR_VERDE);
                this.estadoJLabel.setVisible(true);
            } 
        }else{
            this.estadoJLabel.setText("La palabra no existe no puedes borrarla");
            this.estadoJLabel.setForeground(COLOR_ROJO);
            this.estadoJLabel.setVisible(true);
        }
    }//GEN-LAST:event_borrarJButtomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModificarMotor dialog = new ModificarMotor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadirButtom;
    private javax.swing.JPanel anadirJPanel;
    private javax.swing.JTextField anadirTextField;
    private javax.swing.JPanel borradoJPanel;
    private javax.swing.JButton borrarJButtom;
    private javax.swing.JPanel borrarJPanel;
    private javax.swing.JTextField borrarJText;
    private javax.swing.JPanel cuerpoJPanel;
    private javax.swing.JLabel estadoInsertarJLabel;
    private javax.swing.JPanel estadoInsertarJPanel;
    private javax.swing.JLabel estadoJLabel;
    private javax.swing.JPanel estadoJPanel;
    private javax.swing.JPanel insertarJPanel;
    private javax.swing.JPanel mainJPanel;
    private javax.swing.JLabel tituloJLabel;
    private javax.swing.JPanel tituloJPanel;
    // End of variables declaration//GEN-END:variables
}
